### ISSUE TITLE
[BUG]: Unable to receive email notifications

### ISSUE THREAD

**Issue by mehrab-alam** [torqbit/torqbit#553] opened 2024-12-18 06:23 UTC
- [ ] Invoice
- [ ] enrollment

**Comment by mehrab-alam** [comment] 2024-12-18 06:28
- [ ] Invoice
- [ ] enrollment

**Comment by amezng** [comment] 2024-12-20 05:28
Closing as duplicate of #560

**Closed by amezng** 2024-12-20 05:28 UTC
Labels: bug, dev/backend
